spring:
  application:
    name: wedding-planner-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/weddingplanner
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
